name: Website Building Test

on:
    pull_request:
        branches:
            - dev
        paths:
            - 'website/**'
            - '!website/**/*.md'

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
              with:
                  # SEE: https://github.com/lerna/lerna/issues/2542
                  fetch-depth: '0'

            - name: Install Node.js
              uses: actions/setup-node@1d0ff469b7ec7b3cb9d8673fde0c81c44821de2a # v4
              with:
                  node-version: 18

            - name: Install dependencies
              run: yarn site:build
