name: VS Code Extension Running Test

on:
    pull_request:
        branches:
            - dev
        paths:
            - '.github/workflows/test-vscode.yml'
            - 'vscode/**'

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
              with:
                  # SEE: https://github.com/lerna/lerna/issues/2542
                  fetch-depth: '0'

            - name: Install Xvfb
              run: sudo apt-get update && sudo apt-get install -y xvfb

            - name: Start Xvfb
              run: |
                  Xvfb :99 &
                  echo "DISPLAY=:99.0" >> $GITHUB_ENV

            - name: Install Node.js
              uses: actions/setup-node@0a44ba7841725637a19e28fa30b79a866c81b0a6 # v4
              with:
                  node-version: 20

            - name: Install dependencies
              run: npm ci --legacy-peer-deps && npm run build

            - name: Run tests
              run: cd vscode && npm run vscode:build && npm run vscode:test
