name: VS Code Extension Running Test

on:
    pull_request:
        branches:
            - dev
            - v5
        paths:
            - '.github/workflows/test-vscode.yml'
            - 'vscode/**'

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
              with:
                  # SEE: https://github.com/lerna/lerna/issues/2542
                  fetch-depth: '0'

            - name: Install Xvfb
              run: sudo apt-get update && sudo apt-get install -y xvfb

            - name: Start Xvfb
              run: |
                  Xvfb :99 &
                  echo "DISPLAY=:99.0" >> $GITHUB_ENV

            - name: Install Node.js
              uses: actions/setup-node@1d0ff469b7ec7b3cb9d8673fde0c81c44821de2a # v4
              with:
                  node-version: 20.15

            - name: Install dependencies
              run: npm ci --legacy-peer-deps && npm run build

            - name: Run tests
              run: cd vscode && npm run vscode:build && npm run vscode:test
